import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import BootstrapClient from './components/BootstrapClient';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BootstrapClient />
        <div className="p-4 mb-4 bg-body-tertiary">
          <div className="container-fluid">
            <h1 className="display-5 fw-bold">Welcome to WordFlash</h1>
            <p className="col fs-4">Flashcards are an effective and fast way of learning as it forces people to
              actively recall new information. WordFlash is a web application that helps users learn words in a
              foreign language with the help of flashcards.</p>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
